name: Upload image files to Azure Blob using RBAC

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときに実行

permissions:  # id-token に書き込み権限を付与
  id-token: write
  contents: read

jobs:
  upload-to-blob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure using Service Principal
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Delete all blobs in the Azure 'images' container
      run: |
        az storage blob delete-batch -s 'images' --account-name 0kubost20291002 --auth-mode login

    - name: Upload to Azure Blob
      run: |
        az storage blob upload-batch -d 'images' --account-name 0kubost20291002 -s ./images --auth-mode login
